### ISSUE TITLE
Details on `Install error` when proceeding with `Local update` aren't provided even in logs

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/android_packages_apps_Updater#2]
[blob/64261f1321395d4d27db4be9921e10318ca032fb/app/src/main/java/org/lineageos/updater/UpdateImporter.java#L173](https://github.com/LineageOS/android_packages_apps_Updater/blob/64261f1321395d4d27db4be9921e10318ca032fb/app/src/main/java/org/lineageos/updater/UpdateImporter.java#L173) doesn't bring up the underlying exception.

<details>
<summary>So only get the application backtrace:</summary>

```
09-29 14:48:06.291 11194 13318 E UpdateImporter: Failed to import update package
09-29 14:48:06.291 11194 13318 E UpdateImporter: java.lang.Exception: Verification failed, file has been deleted
09-29 14:48:06.291 11194 13318 E UpdateImporter:    at org.lineageos.updater.UpdateImporter.verifyPackage(UpdateImporter.java:173)
09-29 14:48:06.291 11194 13318 E UpdateImporter:    at org.lineageos.updater.UpdateImporter.lambda$onPicked$2(UpdateImporter.java:96)
09-29 14:48:06.291 11194 13318 E UpdateImporter:    at org.lineageos.updater.UpdateImporter.$r8$lambda$JvEuq_Y8VIMupLlkko0k9A6Amk4(Unknown Source:0)
09-29 14:48:06.291 11194 13318 E UpdateImporter:    at org.lineageos.updater.UpdateImporter$$ExternalSyntheticLambda0.run(Unknown Source:4)
09-29 14:48:06.291 11194 13318 E UpdateImporter:    at java.lang.Thread.run(Thread.java:1012)
```
</details>

Note that the file isn't deleted contrarily to what should be done... or we aren't talking about the same file. Anyway my personal opinion is that the file shouldn't be removed.

[blob/64261f1321395d4d27db4be9921e10318ca032fb/app/src/main/java/org/lineageos/updater/UpdateImporter.java#L172](https://github.com/LineageOS/android_packages_apps_Updater/blob/64261f1321395d4d27db4be9921e10318ca032fb/app/src/main/java/org/lineageos/updater/UpdateImporter.java#L172)

Could investigate Android source code to see possible errors:

https://developer.android.com/reference/android/os/RecoverySystem#verifyPackage(java.io.File,%20android.os.RecoverySystem.ProgressListener,%20java.io.File)

> Parameters
> ...
> <table>
> <tr>
>     <td><code>deviceCertsZipFile</code></td>
>     <td><code>File</code>: the zip file of certificates whose public keys we will accept. Verification succeeds if the package is signed by the private key corresponding to any public key in this file. May be null to use the system default file (currently "/system/etc/security/otacerts.zip").</td>
> </tr>
> </table>

Should precise **the cryptographic signature** concerning the verification error message.

Modifying `/system/etc/security/otacerts.zip` solved install error (I haven't tried `Local update`).

**Comment by Benjamin-Loison** [comment]
However, how have I modified `/system/etc/security/otacerts.zip`? Furthermore, with what method if not *Local update*? Maybe to properly modify this file, if it is not encrypted, proceeding from recovery seems more appropriate.

**Comment by Benjamin-Loison** [comment]
```bash
date && time find -name otacerts.zip; matrix-commander -m 'Find finished!'
```
<details>
<summary>Output:</summary>

```
Sat Jan  4 02:42:49 AM CET 2025
./system/update_engine/otacerts.zip
./out/target/product/merlinx/recovery/root/system/etc/security/otacerts.zip
./out/target/product/merlinx/system/etc/security/otacerts.zip
./out/target/product/merlinx/obj/PACKAGING/target_files_intermediates/lineage_merlinx-target_files-eng.benjamin_loison/RECOVERY/RAMDISK/system/etc/security/otacerts.zip
./out/target/product/merlinx/obj/PACKAGING/target_files_intermediates/lineage_merlinx-target_files-eng.benjamin_loison/SYSTEM/etc/security/otacerts.zip
./out/target/product/merlinx/obj/ETC/otacerts_intermediates/otacerts.zip
./out/target/product/merlinx/obj/ETC/otacerts.recovery_intermediates/otacerts.zip
./cts/tests/tests/os/assets/otacerts.zip

real	0m27.990s
user	0m1.098s
sys	0m3.997s
```
</details>

`./out/target/product/merlinx/system/etc/security/otacerts.zip` seems to be the one I am looking for.

**Comment by Benjamin-Loison** [comment]
I suspect this approach to be dirtier than https://wiki.lineageos.org/signing_builds#test-keys-to-official-or-vice-versa.

**Comment by Benjamin-Loison** [comment]
<details>
<summary>The person:</summary>

```
-----BEGIN PGP MESSAGE-----

hF4DTQa9Wom5MBgSAQdAKwZJU40wWCUkw4fzalaG9uhdVApGbKL+f8FhAnO001ww
nmGlJqk8Sh4bWRQ5f/ncdYzKzNhqiIYiCbaaLEHUSfUW3L/zsVY0Eq4V/oxcmks9
0kEBEWZsOIdIShTrX2qwrQ9/RhIR6J4chwFeSv0cDcezC8LPipaaxHCnZA0jDowe
1zbjNinjR2YuZJSVUUAiNhYH1Q==
=um6T
-----END PGP MESSAGE-----
```
</details>

He was not able to update from the updater app but was unclear why, probably because of signature failed as stated above.

He has not tried push update script, I guess he refers to https://wiki.lineageos.org/devices/merlinx/update/#from-your-pc-via-the-push_update-script-linuxmacos-only.

See [Benjamin-Loison/lineage_wiki/issues/45](https://github.com/Benjamin-Loison/lineage_wiki/issues/45). This `adb sideload` keeps user data but he erased them by testing successfully to reinstall my build from reinstalled native OS.
